# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.


entries:
- title: Sidebar
  product: ilkokuma 
  version: 1.0
  folders:

  
  
  
  
   - title: Tag archives
    output: web
    folderitems:

    - title: Tag archives overview
      url: /mydoc_tag_archives_overview.html
      output: web

      subfolders:
      - title: Tag archive pages
        output: web
        subfolderitems:

        - title: Formatting pages
          url: /tag_formatting.html
          output: web

        - title: Navigation pages
          url: /tag_navigation.html
          output: web

        - title: Content types pages
          url: /tag_content_types.html
          output: web

        - title: Publishing pages
          url: /tag_publishing.html
          output: web

        - title: Special layout pages
          url: /tag_special_layouts.html
          output: web

        - title: Collaboration pages
          url: /tag_collaboration.html
          output: web

        - title: Troubleshooting pages
          url: /tag_troubleshooting.html
          output: web
  
  
  
  
  
  
  
  
  
  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage
      output: pdf
      type: frontmatter

  - title: ilk
    output: web, pdf
    folderitems:
    - title: Product 1 home
      url: /p1_landing_page.html
      output: web

    - title: Sample 1
      url: /p1_sample1.html
      output: web, pdf

    - title: Sample 2
      url: /p1_sample2.html
      output: web, pdf

    - title: Sample 3
      url: /p1_sample3.html
      output: web, pdf

  - title: Another heading
    output: web, pdf

    folderitems:
    - title: Sample 4
      url: /p1_sample4.html
      output: web, pdf

    - title: Sample 5
      url: /p1_sample5.html
      output: web, pdf

    - title: Sample 6
      url: /p1_sample6.html
      output: web, pdf

    - title: Sample 7
      url: /p1_sample7.html
      output: web, pdf
